server: 
  port: 8123
spring: 
  servlet: 
    multipart: 
      max-file-size: 20MB
      max-request-size: 1000MB
  cloud: 
    gateway: 
      discovery: 
        locator: 
          enabled: false
      routes: 
      - id: airmonitoring
        uri: lb://airmonitoring
        predicates: 
          - Path=/air/**
        filters: 
          - StripPrefix=1
      - id: airmonitoringbak
        uri: lb://airmonitoring
        predicates: 
          - Path=/aaa/**
        filters: 
          - StripPrefix=1

  application: 
    name: gateway-service
eureka: 
  instance: 
    prefer-ip-address: true
    instance-id: 192.168.1.7:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client: 
    service-url: 
      defaultZone: http://192.168.1.7:8761/eureka/