server: 
  port: 8762
web: 
  upload-path: /usr/share/nginx/html/imgs/

spring: 
  servlet: 
    multipart: 
      max-file-size: 20MB
      max-request-size: 1000MB
  application:
    name: airmonitoring
  jpa: 
    generate-ddl: false
    show-sql: true
    hibernate: 
      ddl-auto: none
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.88.188:3306/air?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20   
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true

eureka: 
  instance: 
    prefer-ip-address: true
    instance-id: 192.168.1.7:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client: 
    serviceUrl: 
      defaultZone: http://192.168.1.7:8761/eureka/